// <auto-generated />
using GuitarMan.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GuitarMan.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240819155340_AddDescriptionToSongsTable")]
    partial class AddDescriptionToSongsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GuitarMan.Models.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Songs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Artist = "4 Non Blondes",
                            Link = "https://www.youtube.com/watch?v=-7wsYYY1o98",
                            Title = "What's Up?"
                        },
                        new
                        {
                            Id = 2,
                            Artist = "Johnny Cash",
                            Link = "https://www.youtube.com/watch?v=CrQguKCnYTI",
                            Title = "Hurt"
                        },
                        new
                        {
                            Id = 3,
                            Artist = "Neil Young",
                            Link = "https://www.youtube.com/watch?v=U0MKyH48OhU",
                            Title = "Heart of Gold"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
